options:
    legend:
        display: true
    axes:
        x:
            labelString: 'timestamp (sec)'
        y:
            labelString: 'latency (ms)'
properties:
    lines:
        chassis:
            color: 'rgba(241, 113, 112, 0.5)' # red
            borderWidth: 2
            pointRadius: 0
            fill: false
            showLine: true
        localization:
            color: 'rgba(254, 208,114, 0.5)' # yellow
            borderWidth: 2
            pointRadius: 0
            fill: false
            showLine: true
        prediction:
            color: 'rgba(162, 212, 113, 0.5)' # lime green
            borderWidth: 2
            pointRadius: 0
            fill: false
            showLine: true
        perception:
            color: 'rgba(113, 226, 208, 0.5)' # turquoise
            borderWidth: 2
            pointRadius: 0
            fill: false
            showLine: true
        planning:
            color: 'rgba(113, 208, 255, 0.5)' # aqua
            borderWidth: 2
            pointRadius: 0
            fill: false
            showLine: true
        control:
            color: 'rgba(179, 164, 238, 0.5)' # lavender
            borderWidth: 2
            pointRadius: 0
            fill: false
            showLine: true